# Generated by Django 2.2 on 2019-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0024_auto_20190413_2155'),
        ('Users', '0007_auto_20190413_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='Tips.Tag'),
        ),
    ]
