# Generated by Django 2.2 on 2019-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=240)),
                ('location', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('author', models.OneToOneField(on_delete=models.SET(None), to='Users.Profile')),
            ],
        ),
    ]
