# Generated by Django 2.2 on 2019-04-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile'),
        ('Tips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Post',
        ),
    ]
