# Generated by Django 2.2 on 2019-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0002_auto_20190413_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_question',
            field=models.BooleanField(default=True),
        ),
    ]
