# Generated by Django 2.2 on 2019-04-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0003_post_is_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id',
        ),
    ]
