# Generated by Django 2.2 on 2019-04-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0004_auto_20190413_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
    ]
