# Generated by Django 2.2 on 2019-04-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0007_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
            ],
        ),
    ]
