# Generated by Django 2.2 on 2019-04-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0011_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(on_delete=models.SET(None), to='Tips.Location'),
        ),
    ]
