# Generated by Django 2.2 on 2019-04-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0012_auto_20190413_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
