# Generated by Django 2.2 on 2019-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0014_auto_20190413_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.OneToOneField(on_delete=models.SET(None), to='Users.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET(None), to='Tips.Location'),
        ),
    ]
