# Generated by Django 2.2 on 2019-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0015_auto_20190413_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='Tips.Location'),
        ),
    ]
