# Generated by Django 2.2 on 2019-04-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0018_auto_20190413_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
