# Generated by Django 2.2 on 2019-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0024_auto_20190413_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Tips.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Tips.Tag'),
        ),
    ]
